site_name: System Hub

# Repository settings
repo_url: https://github.com/LBS-Vaxjo/D-WeuWeb01
repo_name: SystemHub
edit_uri: edit/main/docs/

# Theme settings
theme:
  name: material
  language: en
  features:
    # Navigation features
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    # Footer
    - navigation.footer
    # Table of contents
    - toc.follow
    # Github integration?
    - content.action.edit
    - content.action.view
    # Content Tabs
    - content.tabs.link

  # Pallettes?
  palette:
    
    # Palette toggle for white mode
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Markdown Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - toc:
      toc_depth: 3

# material/Mkdocs plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true

# Extra features from material?
extra:
  status:
    - new: Recently Added
    - deprecated: Not in use anymore

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LBS-Vaxjo
      name: LBS Växjö's Github