site_name: Webbutveckling 01
theme:
  name: material
  language: sv
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    